#!/usr/bin/env sh
set -e

ARCH=`uname -m`
echo "Detected architecture: $ARCH."

echo "Setting version."
VERSION=`date +%Y%m%d`
echo "Version is $VERSION."

docker build \
  --tag astroswarm/file_manager-$ARCH:$VERSION \
  --tag astroswarm/file_manager-$ARCH:latest \
 ./

echo "Would you like to push this image now (y/n)?"
read release
if [ $release = "y" ]; then
  echo "Pushing to AstroSwarm registry."
  docker push astroswarm/file_manager-$ARCH:$VERSION
  docker push astroswarm/file_manager-$ARCH:latest
fi
